Native support JWT authn for Gitlab CICD Pipelines and optinally pass …
cyberark/conjur-api-go pull request #130
Opened 2022-05-02 06:23 UTC by matthiasjung

…a hostId for JWT based authn

### Desired Outcome

To use Conjur in Gitlab CICD pipelines Summon is a handy tool. But it requires nasty curl-based JWT authentication call for retrieving an access token, which then has to be passed via file to Summon. Summon should simply make use of the JWT token already present in Gitlab. Following the latest Summon enhancements for JWT authentication (supporting kubernetes JWT only), this feature shall be enhanced to support Gitlab CICD Runners.
In addition to the raw authN-functionality Summon JWT authentication shall support passing a HostID in the AuthN request to seperate Secrets for different pipeline environments (dev/test/prod).

### Implemented Changes
Add the env variable CONJUR_AUTHN_JWT_SERVICE, which supports the values 'kubernets' and 'gitlab' and reads the JWT token in the native way required by the service.
Use the env variable CONJUR_AUTHN_JWT_SERVICE_ID to specify the authenticator's service-id (as is at the moment).
Add env-variable CONJUR_AUTHN_JWT_HOST_ID to pass the host-id for JWT authN.

Attention: The code neither compiled nor tested, due to conjur-api-go build errors regarding a missing cuke-master image.
ERROR: for cuke-master  Get "https://registry2.itci.conjur.net/v2/": net/http: request canceled while waiting for connection
### Connected Issue/Story

Resolves - no GitHub issue at the moment.

CyberArk internal issue link: [insert issue ID]()

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ x] The CHANGELOG needs to be updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ x] This PR requires new unit and integration tests to go with the code
  changes. These are not implemented within this PR as all conjur-api-go builds fail dur to an unavailable image.
- [ ] The changes in this PR do not require tests

#### Documentation

- [x ] Docs (`README`s) needs to be updated if this enhancement gets accepted. 
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [ ] This PR does not require updating any documentation

#### Behavior

- [x] This PR changes product behavior and needs to be reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [x ] Security architect needs to review the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2022-05-02 16:52 UTC, imheresamir requested changes
Hi, these changes will require internal discussion and some rework - please do not merge at this time

2022-05-03 06:54 UTC, matthiasjung commented
Hi @imheresamir, @szh,
thanks for picking this up. Background of my rquest is, I quickly want to get rid of JWT authentication with help of curl before being able to use summon. We are demonstrating Conjur to a lot of our internal Gitlab users and this is a real pain.

I decided to follow the design approach startet with the latest release, by defining a service provider, like kubernetes, which knows how to retrieve the JWT. So maybe it will be better to rename the proposed variable CONJUR_AUTHN_JWT_SERVICE to CONJUR_AUTHN_JWT_PROVIDER. As an alternative I'm happy to pass in the JWT directly to summon (env variable or parameter). I'm happy to share my thoughts in your discussion.

With pleasure, I'd like to build conjur-go-api library and summon-conjur executables, but I'm missing some docs on how to do this. At the moment I'm failing with retrieving cuke-master from https://registry2.itci.conjur.net/v2/ (conn timeout). Looks like this is a private repository?
I'd really appreciate some build instructions as I'm more or less guessing at the moment.

Thanks,
Matthias

2022-05-03 19:44 UTC, imheresamir commented
Hi @matthiasjung,

It seems like you can accomplish your goal without these changes by ensuring that the "subject" field (`sub`) of the JWT token is set to the value of `CONJUR_AUTHN_JWT_HOST_ID`. This value should also match the host ID in the loaded Conjur policy. Could you give that a try and let us know if that resolves the issue you are facing? Thanks.

2022-05-04 16:07 UTC, matthiasjung commented
By the way, this is the curl I want to eleminate with this pull request:
curl -s -k -X POST "$CONJUR_URL/authn-jwt/mcicd-gitlab/conjurdemo/$hostId/authenticate" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "jwt=$CI_JOB_JWT" > $CONJUR_AUTHN_TOKEN_FILE'

2022-05-04 20:31 UTC, matthiasjung commented
Hi @imheresamir, yes I considered that. But I don't see a policy structure that allows this approach in an enterprise context. Think of a Gitlab with 500+ projects and much more large scale applications using Conjur. This means, teams will need to manage the assigned policy branch on their own and admins won't be able to manage authenticators for each project. Especially as authenticators need to be added to conjur.yml config file.

2022-05-04 21:43 UTC, infamousjoeg commented
@matthiasjung 

If I'm following this correctly, you want to authenticate an identity based on the namespace and not a specific job to Conjur.  If that's the case, `token-app-property` should be set to `namespace_path`.  You host identity ID would then be `dev` or `prod` depending on the namespace's configured and used in your GitLab instance.  Further authorizations can be placed using annotations on the Host ID to ensure that a specific branch is being executed by adding the annotation `conjur/authn-jwt/service-id/ref: trunk` or whatever branch you want to authorize.  This will create a segregation of duties among branches and secrets for security and compliance purposes.

2022-05-05 03:45 UTC, infamousjoeg commented
```yaml
- !policy
  id: gitlab
  body:

    # Create example secrets for dev and prod namespaces in GitLab
    - !variable secret-for-dev
    - !variable secret-for-prod

    - !host
      id: dev # This should equal the `namespace_path` you want to create an identity for
      annotations:
        # JWT payload must contain claims matching the below
        conjur/authn-jwt/gitlab/ref: dev
        conjur/authn-jwt/gitlab/ref_type: branch

    - !host
      id: prod # This should equal the `namespace_path` you want to create an identity for
      annotations:
        # JWT payload must contain claims matching the below
        conjur/authn-jwt/gitlab/ref: trunk
        conjur/authn-jwt/gitlab/ref_type: branch

    # Permit the dev host access to use the dev secret
    - !permit
      role: !host dev
      privileges: [ read, execute ]
      resource: !variable secret-for-dev

    # Permit the prod host to use the prod secret
    - !permit
      role: !host prod
      privileges: [ read, execute ]
      resource: !variable secret-for-trunk
```

Hopefully the above example policy helps explain what I was talking about in my previous reply.

2022-05-05 07:28 UTC, matthiasjung commented
Hi @infamousjoeg,
thanks for you explanations. They point exactly to my issue, but won't solve. For a 1:1 identity mapping in Conjur a specific job needs to be authenticated for seperating dev and prod secrets.

Authenticating an identity based on `project_path` or `namespace_path` does not allow to differ between dev and prod as a gitlab project will usually deploy to both environments. The claims `project_path` or `namespace_path` are set by gitlab. So I'm failing to identify two hosts (dev and prod) within a project. An exampe: Gitlab project /gitlab/my- app/deployment will result - in exactly one host id, if ` token-app-property` is set to `project_path`
```
- !policy
  id: /gitlab/my- app/
  body:
    - !host
      id: deployment
```

Identifying the job would solve the issue. Unfortunately there is no single JWT claim to be set as` token-app-property` that suits for identifying a job. The `sub `and `job_id `claim are useless because they will change with each pipeline execution. The combination of `namespace_path` and `environment ` (token-app-property = namespace_path/environment) would do this, but this is not supported by Conjur.

This is why I'm friend of passing the desired host id in the auth request.

As a reference, here an exampe JWT payload and some sample pipeline snippets:
```
"payload": {
"namespace_id": "36580",
"namespace_path": "dummy-app",
"project_id": "66056",
"project_path": "dummy-app/conjur-vault-demo",
"user_id": "16475",
"user_login": "mj",
"user_email": "my@example.com",
"pipeline_id": "5904609",
"pipeline_source": "push",
"job_id": "29464756",
"ref": "main",
"ref_type": "branch",
"ref_protected": "true",
"environment": "production",
"environment_protected": "false",
"sub": "job_29464756"
}
```
```
deploy_test:
  environment:
    name: testing
  stage: deploy
  script:
    - summon -f secrets.yml -e testing printenv | grep DB_

deploy_prod:
  environment:
    name: production
  stage: deploy
  script:
    - summon -f secrets.yml -e production printenv | grep DB_
```

2022-05-05 12:26 UTC, infamousjoeg commented
Ah yes, I understand now.  This is unfortunately a limitation due to the JWT payload GitLab job's generate.  A feature request with them to add an additional claim for `job_name` may be warranted to get this resolved.  I spoke with them yesterday and they seem very open to suggestions in how to improve our integration with them.  Coming from a customer would have more priority than myself. 😄

2022-05-05 19:04 UTC, matthiasjung commented
I'm happy my issue is understood. I'll look for contact persons in our company with contacts to Gitlab for addressing this enhancement. Until this gets implemented on Gitlab and deployed on our side a couple of months will pass. Same probably counts for Conjur if `token-app-property` functionality should get enhanced to allow concatination for multiple claims like `namespace_path/environment`.
Summon, or better conjur-api-go can solve this issue quickly by implementing my proposed change adding optional variable CONJUR_AUTHN_JWT_HOST_ID. 
If you agree, I'll revert code changes for CONJUR_AUTHN_JWT_SERVICE_ID and create a new pull request containing only CONJUR_AUTHN_JWT_HOST_ID. Alternativly the 7 lines of code can be copied manually.

2022-05-17 20:08 UTC, imheresamir commented on conjurapi/client.go
> +		jwtToken = os.Getenv("CI_JOB_JWT")
Don't include this

2022-05-17 20:08 UTC, imheresamir commented on conjurapi/client.go
> +	authnJwtService := os.Getenv("CONJUR_AUTHN_JWT_SERVICE")
Remove this conditional

2022-05-17 20:09 UTC, imheresamir commented on conjurapi/client.go
> +		jwt, err := ioutil.ReadFile(jwtTokenPath)
Remove this

2022-05-17 20:09 UTC, imheresamir commented on conjurapi/client.go
> +		authnJwtHostID := os.Getenv("CONJUR_AUTHN_JWT_HOST_ID")
Keep this

2022-05-17 20:18 UTC, szh commented
@matthiasjung I made changes based on the discussion. Please let me know if this would be sufficient for your use case.

In terms of building locally, unfortunately the tests use a docker image for Docker Enterprise which is only available internally via our private registry, so that's not possible right now. Ideally it could be reworked to use Conjur OSS but that's not something likely to be a priority for us anytime soon. Of course any contributions are welcome.

2022-05-19 10:46 UTC, imheresamir commented
@szh mind squashing? ty

2022-05-19 13:13 UTC, szh commented
> @szh mind squashing? ty

Done

2022-05-19 17:18 UTC, imheresamir approved these changes

2022-05-19 17:18 UTC, imheresamir commented
LGTM

2022-05-19 17:19 UTC, merged